# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 09:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(default='main', max_length=100)),
                ('conversion_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_name', models.CharField(max_length=10)),
                ('game_status', models.CharField(choices=[('live', '"live"'), ('closed', '"closed"')], default='closed', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=4000)),
                ('time_of_post', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('stock_price', models.IntegerField(default=0)),
                ('market_type', models.CharField(choices=[('BSE', '"BSE"'), ('NYM', '"NYM"')], default='BSE', max_length=10)),
                ('price_trend', models.IntegerField(default=0)),
                ('initial_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockPurchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_stocks', models.IntegerField(default=0)),
                ('average_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail_id', models.CharField(max_length=100)),
                ('balance', models.IntegerField(default=100)),
                ('net_worth', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockpurchased',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile'),
        ),
        migrations.AddField(
            model_name='stockpurchased',
            name='stockid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Stock'),
        ),
    ]
