# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('price_at_time', models.IntegerField(default=0)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Stock')),
            ],
        ),
    ]
