# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stockpricevariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stocks_sold',
        ),
    ]
