# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180221_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='initial_price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
