# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180129_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='net_worth',
            field=models.IntegerField(default=0),
        ),
    ]
