# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_net_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='initial_price',
            field=models.IntegerField(default=0),
        ),
    ]
