# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180206_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.IntegerField(default=100),
        ),
    ]
