# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180210_0828'),
        ('main', '0008_auto_20180209_1006'),
    ]

    operations = [
    ]
