# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20180210_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market_type',
            field=models.CharField(choices=[('BSE', '"BSE"'), ('NYM', '"NYM"'), ('Both', '"Both"')], default='Both', max_length=10),
        ),
    ]
