# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 12:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180211_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=4000)),
                ('minute_interval', models.IntegerField(default=0)),
                ('corresponding_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Stock')),
            ],
        ),
        migrations.AlterField(
            model_name='newspost',
            name='time_of_post',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 11, 18, 28, 14, 629190)),
        ),
    ]
