# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180216_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='initial_price',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='time_of_post',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 16, 18, 20, 24, 333110)),
        ),
    ]
