# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180216_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='time_of_post',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 16, 19, 29, 48, 84480)),
        ),
    ]
