# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180219_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='time_of_post',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 19, 18, 44, 26, 716233)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_trend',
            field=models.IntegerField(default=0),
        ),
    ]
