# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180219_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(default='main', max_length=100)),
                ('conversion_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='newspost',
            name='time_of_post',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 19, 19, 34, 44, 780180)),
        ),
    ]
