# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20180219_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storednews',
            name='corresponding_stock',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='corresponding_stock',
        ),
        migrations.AlterField(
            model_name='newspost',
            name='time_of_post',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 20, 18, 45, 25, 810655)),
        ),
        migrations.DeleteModel(
            name='StoredNews',
        ),
    ]
