# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_merge_20180220_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameswitch',
            name='game_status',
            field=models.CharField(choices=[('live', '"live"'), ('closed', '"closed"')], default='closed', max_length=100),
        ),
    ]
