# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20180220_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpurchased',
            name='average_price',
            field=models.IntegerField(default=0),
        ),
    ]
