# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_stockpurchased_average_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='initial_price',
            field=models.IntegerField(default=0),
        ),
    ]
