# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180221_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='price_trend',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpurchased',
            name='average_price',
            field=models.IntegerField(default=0),
        ),
    ]
